### PR TITLE
Speed up navigate_to

### PR DESCRIPTION
**Pull request by AethanFoot**

### CODE REVIEW

**Comment by eromatiya** [comment]
Great work! Thank you for this! Will merge this now!

**Comment by eromatiya** [comment]
Hey @AethanFoot, I noticed that the folders/files with whitespace are being cut off. What do you think the problem here? Here's a folder with `Test Folder` name, after searching it, the whitespace and next characters were replaced by `??`. Note that both `fd` and `find` have this problem.

time

**Comment by AethanFoot** [comment]
Try changing the $1 in the awk command to $0

**Comment by eromatiya** [comment]
> Try changing the $1 in the awk command to $0

Thanks! That fixed it! The problem now is that there are now `??` at the end of each results.

**Comment by eromatiya** [comment]
Nevermind, the question marks are from the awk command. Thanks again!

**Pull request merged**
